import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/theme.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0

[font.bold]
family = "FiraCode"
style = "Bold"

[font.bold_italic]
family = "FiraCode"
style = "Bold Italic"

[font.italic]
family = "FiraCode"
style = "Italic"

[font.normal]
family = "FiraCode"
style = "Regular"

[window]
dynamic_padding = true
