return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  lazy = true,
  tag = "v3.17.0",
  opts = {
    icons = {
      breadcrumb = "»", -- symbol used in the command line area that shows your active key combo
      separator = "➜", -- symbol used between a key and it's label
      group = "+", -- symbol prepended to a group
    },
  },
  keys = {
    {
      "<leader>fs",
      function()
        require("aider.aider").send_file()
      end,
      desc = "Send file",
      mode = { "n", "v" },
    },
    {
      "<leader>fl",
      function()
        require("aider.aider").select_template()
      end,
      desc = "List templates",
    },
    {
      "<leader>fo",
      function()
        require("aider.aider").toggle()
      end,
      desc = "Open aider",
    },
    { "<leader>fc", "<cmd>Aider command<cr>", desc = "Aider Commands" },
    { "<leader>fb", "<cmd>Aider buffer<cr>", desc = "Send Buffer" },
    { "<leader>f+", "<cmd>Aider add<cr>", desc = "Add File" },
    { "<leader>f-", "<cmd>Aider drop<cr>", desc = "Drop File" },
    { "<leader>fr", "<cmd>Aider add readonly<cr>", desc = "Add Read-Only" },
    { "<leader>f+", "<cmd>AiderTreeAddFile<cr>", desc = "Add File from Tree to Aider", ft = "NvimTree" },
    { "<leader>f-", "<cmd>AiderTreeDropFile<cr>", desc = "Drop File from Tree from Aider", ft = "NvimTree" },
    {
      "<leader>Da",
      "<cmd>TroubleToggle<cr>",
      desc = "Toggle",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Dd",
      "<cmd>lua require('telescope.builtin').lsp_references()<cr>",
      desc = "LSP References",
      nowait = true,
      remap = false,
    },
    {
      "<leader>De",
      "<cmd>TroubleToggle loclist<cr>",
      desc = "Loclist",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Dq",
      "<cmd>TroubleToggle document_diagnostics<cr>",
      desc = "Document Diagnostics",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Ds",
      "<cmd>TroubleToggle workspace_diagnostics<cr>",
      desc = "Workspace Diagnostics",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Dw",
      "<cmd>TroubleToggle quickfix<cr>",
      desc = "Quickfix",
      nowait = true,
      remap = false,
    },
    {
      "<leader>GA",
      "<cmd>GoRmTag json<cr>",
      desc = "Remove json tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>GB",
      "<cmd>GoRmTag form<cr>",
      desc = "Remove form tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>GF",
      "<cmd>GoRmTag db<cr>",
      desc = "Remove db tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>GI",
      "<cmd>GoRmTag param<cr>",
      desc = "Remove param tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Ga",
      "<cmd>GoAddTag json<cr>",
      desc = "Add json tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gy",
      "<cmd>GoAddTag yaml<cr>",
      desc = "Add yaml tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gb",
      "<cmd>GoAddTag form<cr>",
      desc = "Add form tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gc",
      "<cmd>GoRename<cr>",
      desc = "Renomear variavel",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gd",
      "<cmd>GoFillStruct<cr>",
      desc = "Auto fill struct",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Ge",
      "<cmd>GoIfErr\t<cr>",
      desc = "Add if err",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gf",
      "<cmd>GoAddTag db<cr>",
      desc = "Add db tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gg",
      "<cmd>GoImpl<cr>",
      desc = "Implmenta interface",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gh",
      "<cmd>GoModInit<cr>",
      desc = "go mod init (restart)",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Gi",
      "<cmd>GoAddTag param<cr>",
      desc = "Add param tags",
      nowait = true,
      remap = false,
    },
    {
      "<leader>M",
      "<cmd>MarkdownPreview<cr>",
      desc = "Open Markdown",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Na",
      "<cmd>2TermExec cmd='node %'<cr>",
      desc = "Run current file",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Nb",
      "<cmd>2TermExec cmd='npx ts-node-dev %'<cr>",
      desc = "Run current file with typescript",
      nowait = true,
      remap = false,
    },
    {
      "<leader>P",
      "<cmd>lua require('telescope').extensions.projects.projects()<cr>",
      desc = "Projects",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Tb",
      "<cmd>TSToolsOrganizeImports<CR>",
      desc = "Organize imports",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Tc",
      "<cmd>TSToolsRenameFile<CR>",
      desc = "Typescript Rename File",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Td",
      "<cmd>TSToolsAddMissingImports<CR>",
      desc = "Import all",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Te",
      "<cmd>TSToolsFixAll<CR>",
      desc = "Fix all",
      nowait = true,
      remap = false,
    },
    {
      "<leader>Tm",
      "<cmd>TSToolsRemoveUnusedImports<CR>",
      desc = "Remover imports nao utilizados",
      nowait = true,
      remap = false,
    },
    {
      "<leader>aa",
      '<cmd>lua require("neotest").run.run()<cr>',
      desc = "Run the nearest test",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ab",
      "<cmd>lua require('neotest').summary.toggle()<cr>",
      desc = "Show tests summary",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ao",
      '<cmd>lua require("neotest").output.open({ enter = true, auto_close = true })<cr>',
      desc = "Show Output",
      nowait = true,
      remap = false,
    },

    {
      "<leader>ad",
      "<cmd>lua require('neotest').run.run({strategy = 'dap'})<cr>",
      desc = "Debug the nearest test",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ai",
      "<cmd>lua Integration_test()<cr>",
      desc = "Run current integration test file",
      nowait = true,
      remap = false,
    },
    {
      "<leader>b",
      "<cmd>lua require('telescope').extensions.aerial.aerial()<cr>",
      desc = "File Structure",
      nowait = true,
      remap = false,
    },
    {
      "<leader>c",
      "<cmd>Bdelete!<CR>",
      desc = "Close Buffer",
      nowait = true,
      remap = false,
    },
    {
      "<leader>db",
      "<cmd>Rest open<cr>",
      desc = "Open result pane",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gR",
      "<cmd>lua require 'gitsigns'.reset_buffer()<cr>",
      desc = "Reset Buffer",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gb",
      "<cmd>Telescope git_branches<cr>",
      desc = "Checkout branch",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gc",
      "<cmd>Telescope git_commits<cr>",
      desc = "Checkout commit",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gd",
      "<cmd>Gitsigns diffthis HEAD<cr>",
      desc = "Diff",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gg",
      "<cmd>lua _LAZYGIT_TOGGLE()<CR>",
      desc = "Lazygit",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gj",
      "<cmd>lua require 'gitsigns'.next_hunk()<cr>",
      desc = "Next Hunk",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gk",
      "<cmd>lua require 'gitsigns'.prev_hunk()<cr>",
      desc = "Prev Hunk",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gl",
      "<cmd>lua require 'gitsigns'.blame_line()<cr>",
      desc = "Blame",
      nowait = true,
      remap = false,
    },
    {
      "<leader>go",
      "<cmd>Telescope git_status<cr>",
      desc = "Open changed file",
      nowait = true,
      remap = false,
    },
    {
      "<leader>gp",
      "<cmd>lua require 'gitsigns'.preview_hunk()<cr>",
      desc = "Preview Hunk",
      nowait = true,
      remap = false,
    },
    {
      "<leader>h",
      "<cmd>nohlsearch<CR>",
      desc = "No Highlight",
      nowait = true,
      remap = false,
    },
    {
      "<leader>i",
      "<cmd>set expandtab<cr><cmd>retab!<cr>",
      desc = "Tabs to spaces",
      nowait = true,
      remap = false,
    },
    {
      "<leader>k",
      "<cmd>BufferCloseAllButCurrent<CR>",
      desc = "close all buffers",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lI",
      "<cmd>LspInstallInfo<cr>",
      desc = "Installer Info",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lS",
      "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>",
      desc = "Workspace Symbols",
      nowait = true,
      remap = false,
    },
    {
      "<leader>la",
      "<cmd>lua vim.lsp.buf.code_action()<cr>",
      desc = "Code Action",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lf",
      "<cmd>lua require('conform').format()<cr>",
      desc = "Format",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lh",
      "<cmd>Telescope lsp_document_diagnostics<cr>",
      desc = "Document Diagnostics",
      nowait = true,
      remap = false,
    },
    {
      "<leader>li",
      "<cmd>LspInfo<cr>",
      desc = "Info",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lj",
      "<cmd>lua vim.diagnostic.goto_next()<CR>",
      desc = "Next Diagnostic",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lk",
      "<cmd>lua vim.diagnostic.goto_prev()<cr>",
      desc = "Prev Diagnostic",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ll",
      "<cmd>lua vim.lsp.codelens.run()<cr>",
      desc = "CodeLens Action",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lq",
      "<cmd>lua vim.diagnostic.setloclist()<cr>",
      desc = "Quickfix",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lr",
      "<cmd>lua vim.lsp.buf.rename()<cr>",
      desc = "Rename",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ls",
      "<cmd>Telescope lsp_document_symbols<cr>",
      desc = "Document Symbols",
      nowait = true,
      remap = false,
    },
    {
      "<leader>lw",
      "<cmd>Telescope lsp_workspace_diagnostics<cr>",
      desc = "Workspace Diagnostics",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ma",
      "<cmd>PlantumlOpen<cr>",
      desc = "Start Plant UML",
      nowait = true,
      remap = false,
    },
    {
      "<leader>md",
      "<cmd>PlantumlStop<cr>",
      desc = "Stop",
      nowait = true,
      remap = false,
    },
    {
      "<leader>mp",
      "<cmd>lua _PLANTUML_SAVE_PDF()<cr>",
      desc = "Save PDF",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ms",
      "<cmd>PlantumlSave<cr>",
      desc = "Save PNG",
      nowait = true,
      remap = false,
    },
    {
      "<leader>oa",
      "<cmd>lua require('dapui').open()<cr>",
      desc = "Open",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ob",
      "<cmd>lua require('dapui').close()<cr>",
      desc = "Close",
      nowait = true,
      remap = false,
    },
    {
      "<leader>oc",
      "<cmd>lua require('dapui').close()<cr>",
      desc = "Toggle",
      nowait = true,
      remap = false,
    },
    {
      "<leader>od",
      "<cmd>lua require('dap').toggle_breakpoint()<cr>",
      desc = "Toggle Breakpoint",
      nowait = true,
      remap = false,
    },
    {
      "<leader>oe",
      "<cmd>lua require('dapui').eval()<cr>",
      desc = "Eval",
      nowait = true,
      remap = false,
    },
    {
      "<leader>of",
      "<cmd>lua require('dap').clear_breakpoints()<cr>",
      desc = "Clear ALL Breakpoints",
      nowait = true,
      remap = false,
    },
    {
      "<leader>os",
      "<cmd>lua require('dap').continue()<cr>",
      desc = "Start",
      nowait = true,
      remap = false,
    },
    {
      "<leader>pa",
      "<cmd>2TermExec cmd='python %'<cr>",
      desc = "Run current file",
      nowait = true,
      remap = false,
    },
    {
      "<leader>pb",
      "<cmd>2TermExec cmd='make run'<cr>",
      desc = "Run application",
      nowait = true,
      remap = false,
    },
    {
      "<leader>q",
      "<cmd>q!<cr>",
      desc = "Quit",
      nowait = true,
      remap = false,
    },
    {
      "<leader>ra",
      "<cmd>TroubleToggle<cr>",
      desc = "Toggle",
      nowait = true,
      remap = false,
    },
    {
      "<leader>rd",
      "<cmd>lua require('telescope.builtin').lsp_references()<cr>",
      desc = "LSP References",
      nowait = true,
      remap = false,
    },
    {
      "<leader>re",
      "<cmd>TroubleToggle loclist<cr>",
      desc = "Loclist",
      nowait = true,
      remap = false,
    },
    {
      "<leader>rq",
      "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
      desc = "Document Diagnostics",
      nowait = true,
      remap = false,
    },
    {
      "<leader>rs",
      "<cmd>Trouble diagnostics toggle<cr>",
      desc = "Workspace Diagnostics",
      nowait = true,
      remap = false,
    },
    {
      "<leader>rw",
      "<cmd>TroubleToggle quickfix<cr>",
      desc = "Quickfix",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sC",
      "<cmd>Telescope commands<cr>",
      desc = "Commands",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sM",
      "<cmd>Telescope man_pages<cr>",
      desc = "Man Pages",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sR",
      "<cmd>Telescope registers<cr>",
      desc = "Registers",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sb",
      "<cmd>Telescope git_branches<cr>",
      desc = "Checkout branch",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sc",
      "<cmd>Telescope colorscheme<cr>",
      desc = "Colorscheme",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sh",
      "<cmd>Telescope help_tags<cr>",
      desc = "Find Help",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sk",
      "<cmd>Telescope keymaps<cr>",
      desc = "Keymaps",
      nowait = true,
      remap = false,
    },
    {
      "<leader>sr",
      "<cmd>Telescope oldfiles<cr>",
      desc = "Open Recent File",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tb",
      "<cmd>ToggleTerm direction=tab<cr>",
      desc = "Tab",
      nowait = true,
      remap = false,
    },
    {
      "<leader>td",
      "<cmd>lua _LAZYDOCKER_TOGGLE()<cr>",
      desc = "Lazy Docker",
      nowait = true,
      remap = false,
    },
    {
      "<leader>te",
      "<cmd>lua _START_NGROK()<cr>",
      desc = "Start Ngrok",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tf",
      "<cmd>lua _OPEN_NGROK()<cr>",
      desc = "Open Ngrok",
      nowait = true,
      remap = false,
    },
    {
      "<leader>th",
      "<cmd>ToggleTerm size=10 direction=horizontal<cr>",
      desc = "Horizontal",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tl",
      "<cmd>lua _LAZYGIT_TOGGLE()<cr>",
      desc = "Lazy Git",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tn",
      "<cmd>lua _NODE_TOGGLE()<cr>",
      desc = "Node",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tp",
      "<cmd>lua _PYTHON_TOGGLE()<cr>",
      desc = "Python",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tt",
      "<cmd>lua _HTOP_TOGGLE()<cr>",
      desc = "Htop",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tu",
      "<cmd>lua _NCDU_TOGGLE()<cr>",
      desc = "NCDU",
      nowait = true,
      remap = false,
    },
    {
      "<leader>tv",
      "<cmd>ToggleTerm size=80 direction=vertical<cr>",
      desc = "Vertical",
      nowait = true,
      remap = false,
    },
    {
      "<leader>u",
      "<cmd>set noexpandtab<cr><cmd>retab!<cr>",
      desc = "Spaces to Tabs",
      nowait = true,
      remap = false,
    },
    {
      "<leader>w",
      "<cmd>w!<CR>",
      desc = "Save",
      nowait = true,
      remap = false,
    },
  },
  config = function(_, opts)
    local which_key = require("which-key")
    which_key.setup(opts)
    which_key.add(require("plugins.whichkey_commands.tui"))
    which_key.add(require("plugins.whichkey_commands.json"))
    which_key.add(require("plugins.whichkey_commands.others"))
    which_key.add(require("plugins.whichkey_commands.ai"))
    which_key.add(require("plugins.whichkey_commands.ai"))
    which_key.add(require("plugins.whichkey_commands.requests"))
    which_key.add(require("plugins.whichkey_commands.git"))
    which_key.add({
      {
        "<leader>D",
        group = "Diagnostics",
        nowait = true,
        remap = false,
      },
      {
        "<leader>G",
        group = "Golang",
        nowait = true,
        remap = false,
      },
      {
        "<leader>N",
        group = "Node",
        nowait = true,
        remap = false,
      },
      {
        "<leader>T",
        group = "Typescript",
        nowait = true,
        remap = false,
      },
      {
        "<leader>a",
        group = "Tests",
        nowait = true,
        remap = false,
      },
      {
        "<leader>g",
        group = "Git",
        nowait = true,
        remap = false,
      },
      {
        "<leader>l",
        group = "LSP",
        nowait = true,
        remap = false,
      },
      {
        "<leader>m",
        group = "Plant UML",
        nowait = true,
        remap = false,
      },
      {
        "<leader>o",
        group = "DAP",
        nowait = true,
        remap = false,
      },
      {
        "<leader>p",
        group = "Python",
        nowait = true,
        remap = false,
      },
      {
        "<leader>r",
        group = "Diagnostics",
        nowait = true,
        remap = false,
      },
      {
        "<leader>s",
        group = "Search",
        nowait = true,
        remap = false,
      },
      {
        "<leader>t",
        group = "Terminal",
        nowait = true,
        remap = false,
      },
    })
  end,
}
