return {
	{
		"<leader>l",
		group = "LSP",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lO",
		LazyVim.lsp.action["source.organizeImports"],
		desc = "Organize imports",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lI",
		"<cmd>LspInstallInfo<cr>",
		desc = "Installer Info",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lS",
		"<cmd>Telescope lsp_dynamic_workspace_symbols<cr>",
		desc = "Workspace Symbols",
		nowait = true,
		remap = false,
	},
	{
		"<leader>la",
		"<cmd>lua vim.lsp.buf.code_action()<cr>",
		desc = "Code Action",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lf",
		"<cmd>lua require('conform').format()<cr>",
		desc = "Format",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lh",
		"<cmd>Telescope lsp_document_diagnostics<cr>",
		desc = "Document Diagnostics",
		nowait = true,
		remap = false,
	},
	{
		"<leader>li",
		"<cmd>LspInfo<cr>",
		desc = "Info",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lj",
		"<cmd>lua vim.diagnostic.goto_next()<CR>",
		desc = "Next Diagnostic",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lk",
		"<cmd>lua vim.diagnostic.goto_prev()<cr>",
		desc = "Prev Diagnostic",
		nowait = true,
		remap = false,
	},
	{
		"<leader>ll",
		"<cmd>lua vim.lsp.codelens.run()<cr>",
		desc = "CodeLens Action",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lq",
		"<cmd>lua vim.diagnostic.setloclist()<cr>",
		desc = "Quickfix",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lr",
		"<cmd>lua vim.lsp.buf.rename()<cr>",
		desc = "Rename",
		nowait = true,
		remap = false,
	},
	{
		"<leader>ls",
		group = "Document Symbols",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lsa",
		"<cmd>Telescope lsp_document_symbols<cr>",
		desc = "All",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lsf",
		function()
			require("telescope.builtin").lsp_document_symbols({ symbols = "function" })
		end,
		desc = "Functions",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lsm",
		function()
			require("telescope.builtin").lsp_document_symbols({ symbols = "method" })
		end,
		desc = "Methods",
		nowait = true,
		remap = false,
	},
	{
		"<leader>lw",
		"<cmd>Telescope lsp_workspace_diagnostics<cr>",
		desc = "Workspace Diagnostics",
		nowait = true,
		remap = false,
	},
}
