return {
  {
    "<leader>Tn",
    "<cmd>2TermExec cmd='node %'<cr>",
    desc = "Run current file",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tb",
    "<cmd>2TermExec cmd='npx ts-node-dev %'<cr>",
    desc = "Run current file with typescript",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tp",
    "<cmd>2TermExec cmd='python %'<cr>",
    desc = "Run current file",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tm",
    "<cmd>2TermExec cmd='make run'<cr>",
    desc = "Run application",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tb",
    "<cmd>ToggleTerm direction=tab<cr>",
    desc = "Tab",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Td",
    "<cmd>lua _LAZYDOCKER_TOGGLE()<cr>",
    desc = "Lazy Docker",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Te",
    "<cmd>lua _START_NGROK()<cr>",
    desc = "Start Ngrok",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tf",
    "<cmd>lua _OPEN_NGROK()<cr>",
    desc = "Open Ngrok",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Th",
    "<cmd>ToggleTerm size=10 direction=horizontal<cr>",
    desc = "Horizontal",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tl",
    "<cmd>lua _LAZYGIT_TOGGLE()<cr>",
    desc = "Lazy Git",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tn",
    "<cmd>lua _NODE_TOGGLE()<cr>",
    desc = "Node",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tp",
    "<cmd>lua _PYTHON_TOGGLE()<cr>",
    desc = "Python",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tt",
    "<cmd>lua _HTOP_TOGGLE()<cr>",
    desc = "Htop",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tu",
    "<cmd>lua _NCDU_TOGGLE()<cr>",
    desc = "NCDU",
    nowait = true,
    remap = false,
  },
  {
    "<leader>Tv",
    "<cmd>ToggleTerm size=80 direction=vertical<cr>",
    desc = "Vertical",
    nowait = true,
    remap = false,
  },
}
