- name: Dotfiles location
  debug:
     msg: "Installing dotfile: '{{ dotfiles_location }}'"
- name: Cloning .dotfiles
  become: true 
  ansible.builtin.git:
    repo: 'https://github.com/rfbatista/dotfiles'
    dest: "{{ dotfiles_location }}"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main 
  tags:
    - install
    - dotfiles
    - local
